In [ ]:
'''
БАГИ:
- научиться тянуть время коммента (реплая) - НЕТ ТАКОЙ ИНФЫ 
(можно прописать руками для 2-3 комментов, взяв время между дат соседних постов)
'''

In [53]:
import pandas as pd

In [2]:
# https://docs.python.org/3/library/datetime.html

from datetime import datetime, date, time

# поле дата-время по полям даты и времени
def dttm_by_date_time(link_date, link_time):
    link_dt = datetime.fromisoformat(link_date)
    if link_time in [None, '']:
        link_time_list = [23,59]
    else:
        link_time_list = list(map(int, link_time.split(':')))
    return datetime.combine(link_dt, time(link_time_list[0], link_time_list[1]))

# link_date = date(2012, 3, 7)
link_date = '2012-03-07'
link_time = '20:55'
link_dttm = dttm_by_date_time(link_date, link_time)
link_dttm

datetime.datetime(2012, 3, 7, 20, 55)

# 1. To fix CANDIDATE tables

In [3]:

candidates_conv_1_3 = pd.read_csv('ssmm_candidates_info_conv_1_3.csv', sep='\t', encoding='utf-8')
candidates_conv_1_3 = candidates_conv_1_3[['name','convocation_no','year_stream_no','year_no','stream_no','academic_group_no','program_txt','link_date','link_time','link']]

candidates_conv_1_3

,name,convocation_no,year_stream_no,year_no,stream_no,academic_group_no,program_txt,link_date,link_time,link
0,Левин Андрей,1,1.1,1,1,101.0,Активный участник и организатор различных меро...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
1,Матвеев Дмитрий Александрович,1,1.1,1,1,101.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
2,Власов Артем Андреевич,1,1.2,1,2,107.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
3,Кириллова Полина,1,1.2,1,2,112.0,Мне нравится заниматься общественной деятельно...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
4,Семенов Павел,1,1.2,1,2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",2012-02-26,0:16,https://vk.com/topic-33327655_26089953
...,...,...,...,...,...,...,...,...,...,...
126,Сапунов Кирилл Вячеславович,3,5.3,5,3,525.0,"""В Студсовете я уже два года. В позапрошлом го...",2013-11-17,14:21,https://vk.com/topic-33327655_29117817
127,Самонов Алексей Александрович,3,5.3,5,3,526.0,"""Я студент 5 курса, есть опыт в организации ра...",2013-11-17,14:21,https://vk.com/topic-33327655_29117817
128,Короткин Виталий Владимирович,3,m1,1,0,NaN,"""с сентября 2012-н.в. являюсь председателем СК...",2013-11-17,14:16,https://vk.com/topic-33327655_29117788
129,Буряк Анна Андреевна,3,m1,1,0,NaN,"""Состояла в студсовете в 2010-2011 годах, на п...",2013-11-17,14:16,https://vk.com/topic-33327655_29117788
130,Морозов Сергей Сергеевич,3,m2,2,0,NaN,"""Активно участвую в реализации института курат...",2013-11-17,14:13,https://vk.com/topic-33327655_29117770

In [84]:
ssmm_announcements_conv_4_11 = pd.read_csv('ssmm_announcement_info_conv_4_11_upd.csv', sep='\t', encoding='utf-8')
# ssmm_announcement_info_conv_4_11.csv
# ssmm_announcements_conv_4_11.head()

In [5]:
def conv_no_by_year(year):
    if year >= 2013:
        return year-2010
    else:
        return -1

candidates_conv_4_11 = pd.read_csv('ssmm_candidates_info_conv_4_11.csv', sep='\t', encoding='utf-8')
candidates_conv_4_11['convocation_no'] = candidates_conv_4_11['link_year_no'].apply(lambda x: conv_no_by_year(x))
candidates_conv_4_11 = candidates_conv_4_11.merge(ssmm_announcements_conv_4_11[['link','link_date','link_time']], left_on='link',right_on='link',how='left')
candidates_conv_4_11 = candidates_conv_4_11[['name','convocation_no','year_stream_no','year_no','stream_no','academic_group_no','program_txt','link_date','link_time','link']]

candidates_conv_4_11

,name,convocation_no,year_stream_no,year_no,stream_no,academic_group_no,program_txt,link_date,link_time,link
0,Суркова Анастасия Юрьевна,4,2.2,2,2,209.0,"«Подавая заявку в прошлом году в студсовет, яв...",2014-11-13,21:39,https://vk.com/wall-33327655_2202
1,Денисов Илья Олегович,4,2.2,2,2,207.0,"«Вечер добрый, коллеги!\nЯ бы хотел подать зая...",2014-11-13,21:39,https://vk.com/wall-33327655_2202
2,Тюрина Татьяна Игоревна,4,2.2,2,2,209.0,«Уже во второй раз избираюсь в студенческий со...,2014-11-13,21:39,https://vk.com/wall-33327655_2202
3,Дорман Елена Вячеславовна,4,2.3,2,3,226.0,"«По моему мнению, за прошедший год я не плохо ...",2014-11-13,21:40,https://vk.com/wall-33327655_2203
4,Оськин Александр Андреевич,4,2.3,2,3,225.0,«Прежде всего здравствуйте:)\nНа протяжении по...,2014-11-13,21:40,https://vk.com/wall-33327655_2203
...,...,...,...,...,...,...,...,...,...,...
385,Терехов Михаил Сергеевич,11,6.1,6,1,602.0,За правду!,2021-10-16,10:25,https://vk.com/wall-33327655_9978
386,Поликарпов Александр Валерьевич,11,6.3,6,3,621.0,Был одним из основателей бегового клуба MSU RU...,2021-10-16,10:50,https://vk.com/wall-33327655_9982
387,Каляев Тимур Джанбулатович,11,m1,1,0,NaN,"Всем привет! Я только недавно на мехмате, но х...",2021-10-16,11:20,https://vk.com/wall-33327655_9983
388,Маммагаджиев Руслан Гаджимагомедович,11,m1,1,0,NaN,Долгое время был пикчером профкома мехмата. Се...,2021-10-16,11:20,https://vk.com/wall-33327655_9983
389,Третьякова Екатерина Алексеевна,11,m1,1,0,NaN,Я как человек с немалым опытом в делах организ...,2021-10-16,11:20,https://vk.com/wall-33327655_9983

In [6]:
list_of_df = [candidates_conv_1_3,candidates_conv_4_11]
candidates_conv_1_11 = pd.concat(list_of_df).reset_index().drop(['index'], axis=1)
candidates_conv_1_11

,name,convocation_no,year_stream_no,year_no,stream_no,academic_group_no,program_txt,link_date,link_time,link
0,Левин Андрей,1,1.1,1,1,101.0,Активный участник и организатор различных меро...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
1,Матвеев Дмитрий Александрович,1,1.1,1,1,101.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
2,Власов Артем Андреевич,1,1.2,1,2,107.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
3,Кириллова Полина,1,1.2,1,2,112.0,Мне нравится заниматься общественной деятельно...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953
4,Семенов Павел,1,1.2,1,2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",2012-02-26,0:16,https://vk.com/topic-33327655_26089953
...,...,...,...,...,...,...,...,...,...,...
516,Терехов Михаил Сергеевич,11,6.1,6,1,602.0,За правду!,2021-10-16,10:25,https://vk.com/wall-33327655_9978
517,Поликарпов Александр Валерьевич,11,6.3,6,3,621.0,Был одним из основателей бегового клуба MSU RU...,2021-10-16,10:50,https://vk.com/wall-33327655_9982
518,Каляев Тимур Джанбулатович,11,m1,1,0,NaN,"Всем привет! Я только недавно на мехмате, но х...",2021-10-16,11:20,https://vk.com/wall-33327655_9983
519,Маммагаджиев Руслан Гаджимагомедович,11,m1,1,0,NaN,Долгое время был пикчером профкома мехмата. Се...,2021-10-16,11:20,https://vk.com/wall-33327655_9983
520,Третьякова Екатерина Алексеевна,11,m1,1,0,NaN,Я как человек с немалым опытом в делах организ...,2021-10-16,11:20,https://vk.com/wall-33327655_9983

In [7]:

def key_by_2_fields(f1, f2):
    return str(f1)+'_'+'_'.join(str(f2).split())

In [8]:
candidates_conv_1_11['conv_x_name'] = candidates_conv_1_11.apply(lambda x: key_by_2_fields(x['convocation_no'],x['name']), axis=1)

candidates_conv_1_11 = candidates_conv_1_11.fillna(value={'link_time': '23:59'})
candidates_conv_1_11['link_dttm'] = candidates_conv_1_11.apply(lambda x: dttm_by_date_time(x['link_date'],str(x['link_time'])), axis=1)
candidates_conv_1_11 = candidates_conv_1_11.drop_duplicates()
candidates_conv_1_11

,name,convocation_no,year_stream_no,year_no,stream_no,academic_group_no,program_txt,link_date,link_time,link,conv_x_name,link_dttm
0,Левин Андрей,1,1.1,1,1,101.0,Активный участник и организатор различных меро...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Левин_Андрей,2012-02-26 00:16:00
1,Матвеев Дмитрий Александрович,1,1.1,1,1,101.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Матвеев_Дмитрий_Александрович,2012-02-26 00:16:00
2,Власов Артем Андреевич,1,1.2,1,2,107.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Власов_Артем_Андреевич,2012-02-26 00:16:00
3,Кириллова Полина,1,1.2,1,2,112.0,Мне нравится заниматься общественной деятельно...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Кириллова_Полина,2012-02-26 00:16:00
4,Семенов Павел,1,1.2,1,2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Семенов_Павел,2012-02-26 00:16:00
...,...,...,...,...,...,...,...,...,...,...,...,...
516,Терехов Михаил Сергеевич,11,6.1,6,1,602.0,За правду!,2021-10-16,10:25,https://vk.com/wall-33327655_9978,11_Терехов_Михаил_Сергеевич,2021-10-16 10:25:00
517,Поликарпов Александр Валерьевич,11,6.3,6,3,621.0,Был одним из основателей бегового клуба MSU RU...,2021-10-16,10:50,https://vk.com/wall-33327655_9982,11_Поликарпов_Александр_Валерьевич,2021-10-16 10:50:00
518,Каляев Тимур Джанбулатович,11,m1,1,0,NaN,"Всем привет! Я только недавно на мехмате, но х...",2021-10-16,11:20,https://vk.com/wall-33327655_9983,11_Каляев_Тимур_Джанбулатович,2021-10-16 11:20:00
519,Маммагаджиев Руслан Гаджимагомедович,11,m1,1,0,NaN,Долгое время был пикчером профкома мехмата. Се...,2021-10-16,11:20,https://vk.com/wall-33327655_9983,11_Маммагаджиев_Руслан_Гаджимагомедович,2021-10-16 11:20:00
520,Третьякова Екатерина Алексеевна,11,m1,1,0,NaN,Я как человек с немалым опытом в делах организ...,2021-10-16,11:20,https://vk.com/wall-33327655_9983,11_Третьякова_Екатерина_Алексеевна,2021-10-16 11:20:00

In [9]:
candidates_conv_1_11.to_csv('ssmm_candidates_info_conv_1_11.csv', sep='\t', encoding='utf-8', index=False)
# candidates_conv_1_11.to_csv('../library: main/ssmm_candidates_info_conv_1_11.csv', sep='\t', encoding='utf-8', index=False)

# ПЕРВАЯ ГЛАВНАЯ ТАБЛИЦА

# 2. To fix VOTES tables

In [10]:

ssmm_votes_conv_1 = pd.read_csv('ssmm_votes_info_conv_1.csv', sep='\t', encoding='utf-8')
ssmm_votes_conv_2 = pd.read_csv('ssmm_votes_info_conv_2.csv', sep='\t', encoding='utf-8')
ssmm_votes_conv_3 = pd.read_csv('ssmm_votes_info_conv_3.csv', sep='\t', encoding='utf-8')
ssmm_votes_conv_4_11 = pd.read_csv('ssmm_votes_info_conv_4_11.csv', sep='\t', encoding='utf-8')

In [12]:
# ssmm_votes_conv_4_11.head()

In [9]:
ssmm_results_conv_4_11 = pd.read_csv('ssmm_results_info_conv_4_11.csv', sep='\t', encoding='utf-8')
ssmm_results_conv_4_11.head()

,link,year_x_year_stream,link_date,link_year_no,link_month_no,link_day_no,link_time,year_stream_no,year_no,stream_no,stream_size,voted_cnt,invalid_cnt,NOTA_cnt,organizers
0,https://vk.com/wall-33327655_2250,2014_1.1,2014-11-21,2014,11,21,22:15,1.1,1,1,166,129,10,5,"['Ильёй Денисовым', 'Анастасией Сурковой']"
1,https://vk.com/wall-33327655_2252,2014_1.2,2014-11-21,2014,11,21,22:25,1.2,1,2,136,95,4,6,"['Ираклием Глунчадзе', 'Анастасией Сурковой']"
2,https://vk.com/wall-33327655_2254,2014_1.3,2014-11-21,2014,11,21,22:35,1.3,1,3,138,83,1,2,"['Ираклием Глунчадзе', 'Анастасией Савченко']"
3,https://vk.com/wall-33327655_2329,2014_2.1,2014-11-27,2014,11,27,23:15,2.1,2,1,135,89,1,1,"['Ираклием Глунчадзе', 'Анастасией Сурковой']"
4,https://vk.com/wall-33327655_2215,2014_2.2,2014-11-17,2014,11,17,21:06,2.2,2,2,135,87,0,7,['Глунчадзе Ираклием']

In [11]:
ssmm_votes_conv_1.head()

temp_df = ssmm_votes_conv_1

temp_df = temp_df[['convocation_no', 'name', 'year_stream_no', 'votes_cnt', 'elected_flg','link_date','link_time','link']] # , 'link'
temp_votes_conv_1 = temp_df

temp_votes_conv_1.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,1,Матвеев Дмитрий Александрович,1.1,49.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
1,1,Левин Андрей,1.1,48.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
2,1,Кириллова Полина,1.2,40.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
3,1,Власов Артем Андреевич,1.2,36.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
4,1,Кузнецова Алёна,1.2,28.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953

In [12]:

def full_name_by_short_name1(short_name):
#     ЗАВИСИТ ОТ ВНЕШНЕЙ ТАБЛИЦЫ candidates_conv_1_11
    names_conv3 = list(candidates_conv_1_11['name'][candidates_conv_1_11['convocation_no']==1])
    for full_name in names_conv3:
        if short_name in full_name:
            return full_name

temp_df = temp_votes_conv_1
temp_df['full_name'] = temp_df['name'].apply(lambda x: full_name_by_short_name1(x))
temp_df['max_name'] = temp_df['full_name'].combine_first(temp_df['name'])
temp_df = temp_df.drop(['full_name','name'],axis=1).rename(columns={'max_name':'name'})
# temp_df[:20]

temp_votes_conv_1_upd = temp_df[['convocation_no', 'name', 'year_stream_no', 'votes_cnt', 'elected_flg','link_date','link_time','link']] # , 'link'
temp_votes_conv_1_upd.head()

/var/folders/zh/mnvg84rj3_7413ycjzpn5y8r0000gp/T/ipykernel_11395/1272966670.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['full_name'] = temp_df['name'].apply(lambda x: full_name_by_short_name1(x))
/var/folders/zh/mnvg84rj3_7413ycjzpn5y8r0000gp/T/ipykernel_11395/1272966670.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_df['max_name'] = temp_df['full_name'].combine_first(temp_df['name'])

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,1,Матвеев Дмитрий Александрович,1.1,49.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
1,1,Левин Андрей,1.1,48.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
2,1,Кириллова Полина,1.2,40.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
3,1,Власов Артем Андреевич,1.2,36.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
4,1,Кузнецова Алёна,1.2,28.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953

In [13]:
# ssmm_votes_conv_2.head()

temp_df = ssmm_votes_conv_2

temp_df['votes_cnt'] = temp_df.apply(lambda x: None)
temp_df = temp_df[['convocation_no', 'name', 'year_stream_no', 'votes_cnt', 'elected_flg', 'link_date', 'link_time', 'link']]
temp_votes_conv_2 = temp_df

temp_votes_conv_2.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,2,Остроухова Наталья Владимировна,1.1,NaN,1,2012-11-19,16:13,https://vk.com/wall-33327655_725
1,2,Габидов Александр Сергеевич,1.1,NaN,1,2012-11-19,16:13,https://vk.com/wall-33327655_725
2,2,Дяченко Мария Игоревна,1.1,NaN,1,2012-11-19,16:13,https://vk.com/wall-33327655_725
3,2,Ватутин Кирилл Александрович,1.3,NaN,1,2012-11-19,16:13,https://vk.com/wall-33327655_725
4,2,Никифоров Сергей Игоревич,1.3,NaN,1,2012-11-19,16:13,https://vk.com/wall-33327655_725

In [14]:
# ssmm_votes_conv_3.head()

temp_df = ssmm_votes_conv_3

temp_df['votes_cnt'] = temp_df.apply(lambda x: None)
temp_df = temp_df[['convocation_no', 'name', 'year_stream_no', 'votes_cnt', 'elected_flg', 'link_date', 'link_time', 'link']]
temp_votes_conv_3 = temp_df

temp_votes_conv_3.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,3,Алекберов,1.1,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
1,3,Бурнус,1.1,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
2,3,Денисов,1.2,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
3,3,Суркова,1.2,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
4,3,Тюрина,1.2,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600

In [43]:

def full_name_by_short_name3(short_name):
#     ЗАВИСИТ ОТ ВНЕШНЕЙ ТАБЛИЦЫ candidates_conv_1_11
    names_conv3 = list(candidates_conv_1_11['name'][candidates_conv_1_11['convocation_no']==3])
    for full_name in names_conv3:
        if short_name in full_name:
            return full_name

def fix_alekberov_name(name):
    # incorrect: correct
    correct_names_dict = {
        'Алекберов': 'Алекберов Ибрагим Рустамович',
    }
    if name in correct_names_dict.keys():
        return correct_names_dict[name]
    else:
        return name

temp_votes_conv_3_upd = temp_votes_conv_3
temp_votes_conv_3_upd['name'] = temp_votes_conv_3_upd['name'].apply(lambda x: fix_alekberov_name(x))
temp_votes_conv_3_upd['full_name'] = temp_votes_conv_3_upd['name'].apply(lambda x: full_name_by_short_name3(x))
temp_votes_conv_3_upd['max_name'] = temp_votes_conv_3_upd['full_name'].combine_first(temp_votes_conv_3_upd['name'])
temp_votes_conv_3_upd = temp_votes_conv_3_upd[['convocation_no', 'max_name', 'year_stream_no', 'votes_cnt', 'elected_flg', 'link_date', 'link_time', 'link']].rename(columns={'max_name':'name'})
temp_votes_conv_3_upd.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,3,Алекберов Ибрагим Рустамович,1.1,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
1,3,Бурнус Артём Владимирович,1.1,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
2,3,Денисов Илья Олегович,1.2,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
3,3,Суркова Анастасия Юрьевна,1.2,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600
4,3,Тюрина Татьяна Игоревна,1.2,NaN,1,2013-12-10,1:46,https://vk.com/wall-33327655_1600

In [44]:
list_of_df = [temp_votes_conv_1_upd,temp_votes_conv_2,temp_votes_conv_3_upd]
temp_votes_conv_1_3 = pd.concat(list_of_df).reset_index().drop(['index'], axis=1)
temp_votes_conv_1_3 = temp_votes_conv_1_3[['convocation_no', 'name', 'year_stream_no', 'votes_cnt', 'elected_flg', 'link_date', 'link_time', 'link']]

final_votes_conv_1_3 = temp_votes_conv_1_3
final_votes_conv_1_3.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,1,Матвеев Дмитрий Александрович,1.1,49.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
1,1,Левин Андрей,1.1,48.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
2,1,Кириллова Полина,1.2,40.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
3,1,Власов Артем Андреевич,1.2,36.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953
4,1,Кузнецова Алёна,1.2,28.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953

In [45]:
# reorder

temp_df = ssmm_votes_conv_4_11.merge(ssmm_results_conv_4_11[['link','link_date','link_time']], left_on='link', right_on='link',how='outer')
# temp_df

temp_df['convocation_no'] = temp_df['link_year_no'].apply(lambda x: conv_no_by_year(x))
temp_df = temp_df[['convocation_no', 'name', 'year_stream_no', 'votes_cnt', 'elected_flg', 'link_date', 'link_time', 'link']]
final_votes_conv_4_11 = temp_df

final_votes_conv_4_11.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link
0,4,Суркова Анастасия Юрьевна,2.2,53,1,2014-11-17,21:06,https://vk.com/wall-33327655_2215
1,4,Денисов Илья Олегович,2.2,61,1,2014-11-17,21:06,https://vk.com/wall-33327655_2215
2,4,Тюрина Татьяна Игоревна,2.2,48,1,2014-11-17,21:06,https://vk.com/wall-33327655_2215
3,4,Дорман Елена Вячеславовна,2.3,71,1,2014-11-17,21:21,https://vk.com/wall-33327655_2216
4,4,Оськин Александр Андреевич,2.3,45,1,2014-11-17,21:21,https://vk.com/wall-33327655_2216

In [46]:
list_of_df = [final_votes_conv_1_3,final_votes_conv_4_11]
final_votes_conv_1_11 = pd.concat(list_of_df).reset_index().drop(['index'], axis=1)

final_votes_conv_1_11['conv_x_name'] = final_votes_conv_1_11.apply(lambda x: key_by_2_fields(x['convocation_no'],x['name']), axis=1)

final_votes_conv_1_11 = final_votes_conv_1_11.fillna(value={'link_time': '23:59'})
final_votes_conv_1_11['link_dttm'] = final_votes_conv_1_11.apply(lambda x: dttm_by_date_time(x['link_date'],str(x['link_time'])), axis=1)
final_votes_conv_1_11 = final_votes_conv_1_11.drop_duplicates()

final_votes_conv_1_11

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link,conv_x_name,link_dttm
0,1,Матвеев Дмитрий Александрович,1.1,49.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Матвеев_Дмитрий_Александрович,2012-03-07 20:55:00
1,1,Левин Андрей,1.1,48.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Левин_Андрей,2012-03-07 20:55:00
2,1,Кириллова Полина,1.2,40.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Кириллова_Полина,2012-03-07 20:55:00
3,1,Власов Артем Андреевич,1.2,36.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Власов_Артем_Андреевич,2012-03-07 20:55:00
4,1,Кузнецова Алёна,1.2,28.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Кузнецова_Алёна,2012-03-07 20:55:00
...,...,...,...,...,...,...,...,...,...,...
507,11,Маммагаджиев Руслан Гаджимагомедович,m1,10,1.0,2021-10-20,20:21,https://vk.com/wall-33327655_10018,11_Маммагаджиев_Руслан_Гаджимагомедович,2021-10-20 20:21:00
508,11,Третьякова Екатерина Алексеевна,m1,19,1.0,2021-10-20,20:21,https://vk.com/wall-33327655_10018,11_Третьякова_Екатерина_Алексеевна,2021-10-20 20:21:00
509,11,Мазитова Вероника Рустэмовна,6.1,27,1.0,2021-10-21,15:44,https://vk.com/wall-33327655_10026,11_Мазитова_Вероника_Рустэмовна,2021-10-21 15:44:00
510,11,Терехов Михаил Сергеевич,6.1,16,1.0,2021-10-21,15:44,https://vk.com/wall-33327655_10026,11_Терехов_Михаил_Сергеевич,2021-10-21 15:44:00
511,11,Поликарпов Александр Валерьевич,6.3,43,1.0,2021-10-21,22:02,https://vk.com/wall-33327655_10031,11_Поликарпов_Александр_Валерьевич,2021-10-21 22:02:00

In [47]:
final_votes_conv_1_11.to_csv('ssmm_votes_info_conv_1_11.csv', sep='\t', encoding='utf-8', index=False)

# ВТОРАЯ ГЛАВНАЯ ТАБЛИЦА

# 3. To create UNITED CANDIDATE table

In [48]:
ssmm_candidates_info_conv_1_11 = pd.read_csv('ssmm_candidates_info_conv_1_11.csv', sep='\t', encoding='utf-8')
ssmm_candidates_info_conv_1_11.head()

,name,convocation_no,year_stream_no,year_no,stream_no,academic_group_no,program_txt,link_date,link_time,link,conv_x_name,link_dttm
0,Левин Андрей,1,1.1,1,1,101.0,Активный участник и организатор различных меро...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Левин_Андрей,2012-02-26 00:16:00
1,Матвеев Дмитрий Александрович,1,1.1,1,1,101.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Матвеев_Дмитрий_Александрович,2012-02-26 00:16:00
2,Власов Артем Андреевич,1,1.2,1,2,107.0,NaN,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Власов_Артем_Андреевич,2012-02-26 00:16:00
3,Кириллова Полина,1,1.2,1,2,112.0,Мне нравится заниматься общественной деятельно...,2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Кириллова_Полина,2012-02-26 00:16:00
4,Семенов Павел,1,1.2,1,2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",2012-02-26,0:16,https://vk.com/topic-33327655_26089953,1_Семенов_Павел,2012-02-26 00:16:00

In [49]:
ssmm_votes_info_conv_1_11 = pd.read_csv('ssmm_votes_info_conv_1_11.csv', sep='\t', encoding='utf-8')
ssmm_votes_info_conv_1_11.head()

,convocation_no,name,year_stream_no,votes_cnt,elected_flg,link_date,link_time,link,conv_x_name,link_dttm
0,1,Матвеев Дмитрий Александрович,1.1,49.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Матвеев_Дмитрий_Александрович,2012-03-07 20:55:00
1,1,Левин Андрей,1.1,48.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Левин_Андрей,2012-03-07 20:55:00
2,1,Кириллова Полина,1.2,40.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Кириллова_Полина,2012-03-07 20:55:00
3,1,Власов Артем Андреевич,1.2,36.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Власов_Артем_Андреевич,2012-03-07 20:55:00
4,1,Кузнецова Алёна,1.2,28.0,1.0,2012-03-07,20:55,https://vk.com/topic-33327655_26089953,1_Кузнецова_Алёна,2012-03-07 20:55:00

In [50]:
df1 = ssmm_candidates_info_conv_1_11[['conv_x_name','name']]
df2 = ssmm_votes_info_conv_1_11[['conv_x_name','name']]

df1_x_d2 = df1.merge(df2, left_on='conv_x_name', right_on='conv_x_name',how='outer')
df1_x_d2_nan = df1_x_d2[df1_x_d2.isna().any(axis=1)]
df1_x_d2_nan

,conv_x_name,name_x,name_y
46,2_Николаева_Наталия_Михайловна,Николаева Наталия Михайловна,NaN
49,2_Ванунц_Арсений_Ашотович,Ванунц Арсений Ашотович,NaN
56,2_Медведева_Яна_Григорьевна,Медведева Яна Григорьевна,NaN
60,2_Сафина_Диана_Ураловна,Сафина Диана Ураловна,NaN
74,2_Ласкин_Алексей_Александрович,Ласкин Алексей Александрович,NaN
89,3_Корно_Дмитрий_Сергеевич,Корно Дмитрий Сергеевич,NaN
90,3_Изимова_Анна_Мирбулатовна,Изимова Анна Мирбулатовна,NaN
91,3_Чистяков_Михаил_Сергеевич,Чистяков Михаил Сергеевич,NaN
109,3_Заболотский_Леонид_Дмитриевич,Заболотский Леонид Дмитриевич,NaN
110,3_Скопинцев_Алексей_Владимирович,Скопинцев Алексей Владимирович,NaN
262,6_Думаревский_Александр_Дмитриевич,Думаревский Александр Дмитриевич,NaN
396,9_Воронин_Вадим_Юрьевич,Воронин Вадим Юрьевич,NaN
521,1_Федорова_Елена_Игоревна,NaN,Федорова Елена Игоревна
522,3_Алекберов_Ибрагим_Рустамович,NaN,Алекберов Ибрагим Рустамович
523,4_Вергазов_Марат_Марсович,NaN,Вергазов Марат Марсович

In [79]:
# ОБЩАЯ ТАБЛИЦА КАНДИДАТОВ С АНОНСАМИ И ГОЛОСАМИ

temp_df = ssmm_candidates_info_conv_1_11[['conv_x_name','name','convocation_no','year_stream_no','academic_group_no','program_txt','link','link_dttm']].merge(ssmm_votes_info_conv_1_11[['conv_x_name','name','convocation_no','year_stream_no','votes_cnt','elected_flg','link','link_dttm']], left_on='conv_x_name',right_on='conv_x_name',how='outer')

for word in ['name','convocation_no','year_stream_no']:
    temp_df[word] = temp_df[word+'_x'].combine_first(temp_df[word+'_y'])
    temp_df = temp_df.drop([word+'_x', word+'_y'],axis=1)

# temp_df['academic_group_no'] = temp_df['academic_group_no'].apply(lambda x: int(x))
temp_df['convocation_no'] = temp_df['convocation_no'].apply(lambda x: int(x))

temp_df = temp_df.rename(columns={'link_x':'announcement_link','link_y':'result_link','link_dttm_x':'announcement_dttm','link_dttm_y':'result_dttm'})
temp_df['appearance_dttm'] = temp_df['announcement_dttm'].combine_first(temp_df['result_dttm'])

# ДОБАВИТЬ elected_flg = 1 для 5 курса 1 созыва
# temp_df['elected_flg'].mask((temp_df['year_stream_no'].apply(lambda x: x[0] == '5')) & (temp_df['convocation_no'] == 1), 1, inplace=True)

temp_df['elected_flg'] = temp_df['elected_flg'].fillna(0)
temp_df['elected_flg'] = temp_df['elected_flg'].apply(lambda x: int(x))
# temp_df['classic_year_no'] = temp_df['year_stream_no'].apply(lambda x: define_classic_year_no(x))
# temp_df['votes_cnt'] = temp_df['votes_cnt'].apply(lambda x: int(x))
# temp_df['elected_flg'] = temp_df['elected_flg'][temp_df['elected_flg'].notna()].astype('int')
# temp_df['votes_cnt'] = temp_df['votes_cnt'][temp_df['votes_cnt'].notna()].astype('int')
# temp_df['votes_cnt'] = temp_df['votes_cnt'].notna().astype('int')
# temp_df['academic_group_no'] = temp_df['academic_group_no'].notna().astype('int')

ssmm_candidates_x_votes_info_conv_1_11 = temp_df[['conv_x_name','name','convocation_no','year_stream_no','academic_group_no','program_txt','announcement_link','announcement_dttm','votes_cnt','elected_flg','result_link','result_dttm','appearance_dttm']].drop_duplicates()
ssmm_candidates_x_votes_info_conv_1_11

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
2,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
3,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
4,1_Семенов_Павел,Семенов Павел,1,1.2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,20.0,0,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,11_Маммагаджиев_Руслан_Гаджимагомедович,Маммагаджиев Руслан Гаджимагомедович,11,m1,NaN,Долгое время был пикчером профкома мехмата. Се...,https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,10.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
520,11_Третьякова_Екатерина_Алексеевна,Третьякова Екатерина Алексеевна,11,m1,NaN,Я как человек с немалым опытом в делах организ...,https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,19.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
521,1_Федорова_Елена_Игоревна,Федорова Елена Игоревна,1,4.4,NaN,NaN,NaN,NaN,20.0,1,https://vk.com/topic-33327655_26089874,2012-03-07 18:55:00,2012-03-07 18:55:00
522,3_Алекберов_Ибрагим_Рустамович,Алекберов Ибрагим Рустамович,3,1.1,NaN,NaN,NaN,NaN,NaN,1,https://vk.com/wall-33327655_1600,2013-12-10 01:46:00,2013-12-10 01:46:00
523,4_Вергазов_Марат_Марсович,Вергазов Марат Марсович,4,m2,NaN,NaN,NaN,NaN,5.0,1,https://vk.com/wall-33327655_2313,2014-11-25 23:24:00,2014-11-25 23:24:00

In [80]:
ssmm_candidates_x_votes_info_conv_1_11[['program_txt', 'comment_txt']] = ssmm_candidates_x_votes_info_conv_1_11['program_txt'].str.split('\nКомментарий студсовета: ', expand=True)
ssmm_candidates_x_votes_info_conv_1_11.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm,comment_txt
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00,None
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00,NaN
2,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00,NaN
3,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00,None
4,1_Семенов_Павел,Семенов Павел,1,1.2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,20.0,0,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00,None

In [82]:
# ssmm_candidates_x_votes_info_conv_1_11[ssmm_candidates_x_votes_info_conv_1_11['comment_txt'].notna()]

In [83]:
ssmm_candidates_x_votes_info_conv_1_11.to_csv('ssmm_candidates_x_votes_info_conv_1_11.csv', sep='\t', encoding='utf-8', index=False)
ssmm_candidates_x_votes_info_conv_1_11.to_csv('../library: main/ssmm_elections_candidates_1_11.csv', sep='\t', encoding='utf-8', index=False)

# САМАЯ ГЛАВНАЯ ТАБЛИЦА

# 4. To fix ORGANIZER table

In [29]:
ssmm_organizers_info = pd.read_csv('ssmm_organizers_info_conv_4_11.csv', sep='\t', encoding='utf-8')
ssmm_organizers_info.head()

  year_x_year_stream           organizers
0           2014_1.1      Ильёй Денисовым
1           2014_1.1  Анастасией Сурковой
2           2014_1.2   Ираклием Глунчадзе
3           2014_1.2  Анастасией Сурковой
4           2014_1.3   Ираклием Глунчадзе

In [30]:
def find_organizer_origin(organizer_name):
#     ИСПОЛЬЗУЕТСЯ ВНЕШНЯЯ ТАБЛИЦА ssmm_candidates_x_votes_info_conv_1_11
    full_name_list = list(ssmm_candidates_x_votes_info_conv_1_11['name'])
    organizer_name = organizer_name.replace('Воробьевой Наталией','Воробьёвой Натальей')
    organizer_name_list = [word.replace('Павлом','Павел').replace('Корней','Провидухина')[:-2].replace('Петр','Пётр') for word in organizer_name.split()]
#     print(organizer_name_list)
    correct_full_name = None
    for full_name in full_name_list:
        k = 0
        for word in organizer_name_list:
            if word in full_name:
                k += 1
        if k == len(organizer_name_list):
            correct_full_name = full_name
            break
    return correct_full_name

# organizer_name = 'Анастасией Сурковой'
# find_organizer_origin(organizer_name)

In [31]:
ssmm_organizers_info_names = ssmm_organizers_info.groupby(['organizers']).agg({'year_x_year_stream':'count'}).reset_index().rename(columns={'year_x_year_stream':'elections_cnt'}).sort_values(['elections_cnt'],
              ascending = [False]).reset_index().drop(['index'], axis=1)

ssmm_organizers_info_names['full_name'] = ssmm_organizers_info_names['organizers'].apply(lambda x: find_organizer_origin(x))
# ssmm_organizers_info_names[:60]
# ssmm_organizers_info_names[60:]

# баг распознавания в organizers (костыльно преодолен):
# Владиславом Бун

In [32]:
ssmm_organizers_info_upd = ssmm_organizers_info.merge(ssmm_organizers_info_names[['organizers','full_name']],left_on='organizers',right_on='organizers',how='left').rename(columns={'full_name':'organizer_name'}).drop(['organizers'],axis=1)
ssmm_organizers_info_upd = ssmm_organizers_info_upd[ssmm_organizers_info_upd['organizer_name'] != None] # не работает

ssmm_organizers_info_upd.head()
# [:60]

  year_x_year_stream                 organizer_name
0           2014_1.1          Денисов Илья Олегович
1           2014_1.1      Суркова Анастасия Юрьевна
2           2014_1.2  Глунчадзе Ираклий Вахтангович
3           2014_1.2      Суркова Анастасия Юрьевна
4           2014_1.3  Глунчадзе Ираклий Вахтангович

In [35]:
ssmm_organizers_info_upd.to_csv('ssmm_organizers_info_conv_4_11_upd.csv', sep='\t', encoding='utf-8', index=False)
ssmm_organizers_info_upd.to_csv('../library: main/ssmm_organizers_1_11.csv', sep='\t', encoding='utf-8', index=False)

In [64]:
# ssmm_organizers_info = pd.read_csv('../library: main/ssmm_organizers_1_11.csv', sep='\t', encoding='utf-8')
# ssmm_organizers_info.head()

  year_x_year_stream                 organizer_name
0           2014_1.1          Денисов Илья Олегович
1           2014_1.1      Суркова Анастасия Юрьевна
2           2014_1.2  Глунчадзе Ираклий Вахтангович
3           2014_1.2      Суркова Анастасия Юрьевна
4           2014_1.3  Глунчадзе Ираклий Вахтангович

In [66]:
# link_time_list = list(map(int, link_time.split(':')))

def year_to_conv(year_no):
    if year_no >= 2013:
        return year_no - 2010
    else:
        return 0

ssmm_organizers_info[['year','year_stream_no']] = ssmm_organizers_info['year_x_year_stream'].str.split('_',expand=True)
ssmm_organizers_info['convocation_no'] = ssmm_organizers_info['year'].apply(lambda x: year_to_conv(int(x)))
ssmm_organizers_info = ssmm_organizers_info.drop(['year_x_year_stream','year'],axis=1)
ssmm_organizers_info.head()

                  organizer_name year_stream_no  convocation_no
0          Денисов Илья Олегович            1.1               4
1      Суркова Анастасия Юрьевна            1.1               4
2  Глунчадзе Ираклий Вахтангович            1.2               4
3      Суркова Анастасия Юрьевна            1.2               4
4  Глунчадзе Ираклий Вахтангович            1.3               4

In [69]:
ssmm_dict_year_stream = pd.read_csv('../dictionaries/ssmm_dict_year_stream.csv', sep='\t', encoding='utf-8')

ys_df = ssmm_dict_year_stream[['year_stream_no','year_no','stream_no']]
ssmm_organizers_info_2 = ssmm_organizers_info.merge(ys_df, how='left')

ssmm_organizers_info_2 = ssmm_organizers_info_2[ssmm_organizers_info_2.organizer_name.notna()]

ssmm_organizers_info_2
# .head()

,organizer_name,year_stream_no,convocation_no,year_no,stream_no
0,Денисов Илья Олегович,1.1,4,1,1
1,Суркова Анастасия Юрьевна,1.1,4,1,1
2,Глунчадзе Ираклий Вахтангович,1.2,4,1,2
3,Суркова Анастасия Юрьевна,1.2,4,1,2
4,Глунчадзе Ираклий Вахтангович,1.3,4,1,3
...,...,...,...,...,...
286,Мельникова Дарья Владимировна,6.1,11,6,1
287,Малиновский Георгий Андреевич,6.3,11,6,3
288,Третьяков Пётр Максимович,6.3,11,6,3
289,Малиновский Георгий Андреевич,m1,11,1,0
290,Третьяков Пётр Максимович,m1,11,1,0

In [70]:
ssmm_organizers_info_2.to_csv('../library: main/ssmm_organizers_1_11.csv', sep='\t', encoding='utf-8', index=False)

In [ ]:
# НЕ ХВАТАЕТ СВОДНЫХ ПО ПОТОКАМ:
#     - announcements
#     - results

# 5. To fix RESULTS table

In [57]:

def conv_no_by_year(year):
    if year >= 2013:
        return year-2010
    else:
        return -1

In [56]:

ssmm_results_info_conv_4_11 = pd.read_csv('ssmm_results_info_conv_4_11.csv', sep='\t', encoding='utf-8')
ssmm_results_info_conv_4_11.head()

,link,year_x_year_stream,link_date,link_year_no,link_month_no,link_day_no,link_time,year_stream_no,year_no,stream_no,stream_size,voted_cnt,invalid_cnt,NOTA_cnt,organizers
0,https://vk.com/wall-33327655_2250,2014_1.1,2014-11-21,2014,11,21,22:15,1.1,1,1,166,129,10,5,"['Ильёй Денисовым', 'Анастасией Сурковой']"
1,https://vk.com/wall-33327655_2252,2014_1.2,2014-11-21,2014,11,21,22:25,1.2,1,2,136,95,4,6,"['Ираклием Глунчадзе', 'Анастасией Сурковой']"
2,https://vk.com/wall-33327655_2254,2014_1.3,2014-11-21,2014,11,21,22:35,1.3,1,3,138,83,1,2,"['Ираклием Глунчадзе', 'Анастасией Савченко']"
3,https://vk.com/wall-33327655_2329,2014_2.1,2014-11-27,2014,11,27,23:15,2.1,2,1,135,89,1,1,"['Ираклием Глунчадзе', 'Анастасией Сурковой']"
4,https://vk.com/wall-33327655_2215,2014_2.2,2014-11-17,2014,11,17,21:06,2.2,2,2,135,87,0,7,['Глунчадзе Ираклием']

In [58]:
# поправить ключ для ssmm_results_info_conv_4_11.csv

df = ssmm_results_info_conv_4_11
df['convocation_no'] = df['link_year_no'].apply(lambda x: conv_no_by_year(x))

ssmm_results_info_conv_4_11_upd = df[['convocation_no','year_stream_no','stream_size','voted_cnt','NOTA_cnt','invalid_cnt','link','link_date','link_time']]
ssmm_results_info_conv_4_11_upd

,convocation_no,year_stream_no,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,link,link_date,link_time
0,4,1.1,166,129,5,10,https://vk.com/wall-33327655_2250,2014-11-21,22:15
1,4,1.2,136,95,6,4,https://vk.com/wall-33327655_2252,2014-11-21,22:25
2,4,1.3,138,83,2,1,https://vk.com/wall-33327655_2254,2014-11-21,22:35
3,4,2.1,135,89,1,1,https://vk.com/wall-33327655_2329,2014-11-27,23:15
4,4,2.2,135,87,7,0,https://vk.com/wall-33327655_2215,2014-11-17,21:06
...,...,...,...,...,...,...,...,...,...
141,11,5.3,89,46,1,0,https://vk.com/wall-33327655_9912,2021-10-12,20:20
142,11,5.4,37,21,0,0,https://vk.com/wall-33327655_9878,2021-10-06,20:36
143,11,6.1,87,44,6,0,https://vk.com/wall-33327655_10026,2021-10-21,15:44
144,11,6.3,93,47,3,0,https://vk.com/wall-33327655_10031,2021-10-21,22:02
145,11,m1,51,26,3,0,https://vk.com/wall-33327655_10018,2021-10-20,20:21

In [44]:

ssmm_results_info_conv_1 = pd.read_csv('ssmm_results_info_conv_1.csv', sep='\t', encoding='utf-8')
ssmm_results_info_conv_1.head()

,convocation_no,year_stream_no,stream_size,voted_cnt,NOTA_cnt,link,link_date,link_time
0,1,1.1,139,68,6,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
1,1,1.2,138,60,2,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
2,1,1.3,115,73,5,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
3,1,2.1,133,91,5,https://vk.com/topic-33327655_26089854,2012-02-28,22:34
4,1,2.2,111,60,3,https://vk.com/topic-33327655_26089854,2012-02-28,22:34

In [75]:
list_of_df = [ssmm_results_info_conv_1,ssmm_results_info_conv_4_11_upd]
df = pd.concat(list_of_df).reset_index().drop(['index'], axis=1)
df = df[['convocation_no','year_stream_no','stream_size','voted_cnt','NOTA_cnt','invalid_cnt','link','link_date','link_time']]
df['convocation_no'] = df['convocation_no'].apply(lambda x: int(x))
df['year_stream_no'] = df['year_stream_no'].apply(lambda x: str(x))

ssmm_results_info_conv_1_and_4_11 = df
ssmm_results_info_conv_1_and_4_11

,convocation_no,year_stream_no,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,link,link_date,link_time
0,1,1.1,139,68,6,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
1,1,1.2,138,60,2,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
2,1,1.3,115,73,5,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
3,1,2.1,133,91,5,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34
4,1,2.2,111,60,3,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34
...,...,...,...,...,...,...,...,...,...
155,11,5.3,89,46,1,0.0,https://vk.com/wall-33327655_9912,2021-10-12,20:20
156,11,5.4,37,21,0,0.0,https://vk.com/wall-33327655_9878,2021-10-06,20:36
157,11,6.1,87,44,6,0.0,https://vk.com/wall-33327655_10026,2021-10-21,15:44
158,11,6.3,93,47,3,0.0,https://vk.com/wall-33327655_10031,2021-10-21,22:02
159,11,m1,51,26,3,0.0,https://vk.com/wall-33327655_10018,2021-10-20,20:21

In [76]:
ssmm_results_info_conv_1_and_4_11.to_csv('ssmm_results_1_and_4_11.csv', sep='\t', encoding='utf-8', index=False)
# ssmm_results_info_conv_1_and_4_11.to_csv('../library: main/ssmm_results_1_and_4_11.csv', sep='\t', encoding='utf-8', index=False)

# 6. To fix ANNOUNCEMENTS table

In [85]:
ssmm_announcements_conv_4_11 = pd.read_csv('ssmm_announcement_info_conv_4_11_upd.csv', sep='\t', encoding='utf-8')
ssmm_announcements_conv_4_11.head()

,link,year_x_year_stream,link_date,link_year_no,link_month_no,link_day_no,link_time,year_stream_no,year_no,stream_no,election_date
0,https://vk.com/wall-33327655_2220,2014_1.1,2014-11-18,2014,11,18,23:10,1.1,1,1,2014-11-19
1,https://vk.com/wall-33327655_3417,2015_1.1,2015-10-20,2015,10,20,22:15,1.1,1,1,2015-10-21
2,https://vk.com/wall-33327655_5109,2016_1.1,2016-10-16,2016,10,16,21:04,1.1,1,1,2016-10-17
3,https://vk.com/wall-33327655_5261,2016_1.1,2016-10-23,2016,10,23,20:02,1.1,1,1,2016-10-24
4,https://vk.com/wall-33327655_6656,2017_1.1,2017-10-26,2017,10,26,23:23,1.1,1,1,2017-10-27

In [86]:
# поправить ключ для ssmm_results_info_conv_4_11.csv

df = ssmm_announcements_conv_4_11
df['convocation_no'] = df['link_year_no'].apply(lambda x: conv_no_by_year(x))

ssmm_announcements_conv_4_11_upd = df[['convocation_no','year_stream_no','year_no','stream_no','link','link_date','link_time','election_date']]
ssmm_announcements_conv_4_11_upd

,convocation_no,year_stream_no,year_no,stream_no,link,link_date,link_time,election_date
0,4,1.1,1,1,https://vk.com/wall-33327655_2220,2014-11-18,23:10,2014-11-19
1,5,1.1,1,1,https://vk.com/wall-33327655_3417,2015-10-20,22:15,2015-10-21
2,6,1.1,1,1,https://vk.com/wall-33327655_5109,2016-10-16,21:04,2016-10-17
3,6,1.1,1,1,https://vk.com/wall-33327655_5261,2016-10-23,20:02,2016-10-24
4,7,1.1,1,1,https://vk.com/wall-33327655_6656,2017-10-26,23:23,2017-10-27
...,...,...,...,...,...,...,...,...
159,5,m2,2,0,https://vk.com/wall-33327655_3187,2015-10-13,10:40,2015-10-13
160,5,m2,2,0,https://vk.com/wall-33327655_3364,2015-10-20,0:45,2015-10-20
161,6,m2,2,0,https://vk.com/wall-33327655_5157,2016-10-18,1:27,2016-10-18
162,9,m2,2,0,https://vk.com/wall-33327655_8310,2019-10-22,1:46,2019-10-22
163,10,m2,2,0,https://vk.com/wall-33327655_9152,2020-10-30,10:32,2020-10-30

In [87]:

df = pd.read_csv('ssmm_candidates_info_conv_1_3.csv', sep='\t', encoding='utf-8')
ssmm_announcements_conv_1_3 = df[['convocation_no','year_stream_no','year_no','stream_no','link','link_date','link_time']].drop_duplicates()
ssmm_announcements_conv_1_3['election_date'] = None

ssmm_announcements_conv_1_3.head()

,convocation_no,year_stream_no,year_no,stream_no,link,link_date,link_time,election_date
0,1,1.1,1,1,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,None
2,1,1.2,1,2,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,None
6,1,1.3,1,3,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,None
11,1,2.1,2,1,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,None
15,1,2.2,2,2,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,None

In [88]:
list_of_df = [ssmm_announcements_conv_1_3,ssmm_announcements_conv_4_11_upd]
df = pd.concat(list_of_df).reset_index().drop(['index'], axis=1)
df = df[['convocation_no','year_stream_no','year_no','stream_no','link','link_date','link_time','election_date']]
df['convocation_no'] = df['convocation_no'].apply(lambda x: int(x))

ssmm_announcements_conv_1_11 = df
ssmm_announcements_conv_1_11

,convocation_no,year_stream_no,year_no,stream_no,link,link_date,link_time,election_date
0,1,1.1,1,1,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,None
1,1,1.2,1,2,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,None
2,1,1.3,1,3,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,None
3,1,2.1,2,1,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,None
4,1,2.2,2,2,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,None
...,...,...,...,...,...,...,...,...
211,5,m2,2,0,https://vk.com/wall-33327655_3187,2015-10-13,10:40,2015-10-13
212,5,m2,2,0,https://vk.com/wall-33327655_3364,2015-10-20,0:45,2015-10-20
213,6,m2,2,0,https://vk.com/wall-33327655_5157,2016-10-18,1:27,2016-10-18
214,9,m2,2,0,https://vk.com/wall-33327655_8310,2019-10-22,1:46,2019-10-22
215,10,m2,2,0,https://vk.com/wall-33327655_9152,2020-10-30,10:32,2020-10-30

In [89]:
ssmm_announcements_conv_1_11.to_csv('ssmm_announcements_conv_1_11.csv', sep='\t', encoding='utf-8', index=False)
# ssmm_announcements_conv_1_11.to_csv('../library: main/ssmm_announcements_1_11.csv', sep='\t', encoding='utf-8', index=False)

In [90]:
ssmm_results_info_conv_1_and_4_11 = pd.read_csv('ssmm_results_1_and_4_11.csv', sep='\t', encoding='utf-8')
ssmm_results_info_conv_1_and_4_11.head()
# ssmm_results_1_and_4_11

,convocation_no,year_stream_no,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,link,link_date,link_time
0,1,1.1,139,68,6,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
1,1,1.2,138,60,2,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
2,1,1.3,115,73,5,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
3,1,2.1,133,91,5,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34
4,1,2.2,111,60,3,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34

# 7. To create UNITED STREAM table

In [91]:
united_df = ssmm_announcements_conv_1_11.merge(ssmm_results_info_conv_1_and_4_11, left_on=['convocation_no','year_stream_no'], right_on=['convocation_no','year_stream_no'], how='outer')
united_df = united_df.rename(columns={
    'link_x':'announcement_link',
    'link_y':'result_link',
    'link_date_x':'announcement_link_date',
    'link_date_y':'result_link_date',
    'link_time_x':'announcement_link_time',
    'link_time_y':'result_link_time',
})

ssmm_stream_elections_1_11 = united_df
# ssmm_stream_elections_1_11[:20]

In [108]:
ssmm_stream_elections_1_11[-5:]

,convocation_no,year_stream_no,year_no,stream_no,announcement_link,announcement_link_date,announcement_link_time,election_date,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,result_link,result_link_date,result_link_time
214,9,m2,2.0,0.0,https://vk.com/wall-33327655_8310,2019-10-22,1:46,2019-10-22,28.0,18.0,1.0,0.0,https://vk.com/wall-33327655_8372,2019-10-27,22:40
215,10,m2,2.0,0.0,https://vk.com/wall-33327655_9152,2020-10-30,10:32,2020-10-30,18.0,12.0,0.0,0.0,https://vk.com/wall-33327655_9310,2020-11-07,22:38
216,1,3.4,NaN,NaN,NaN,NaN,NaN,NaN,29.0,21.0,21.0,NaN,https://vk.com/topic-33327655_26089737,2012-03-07,2:03
217,1,4.4,NaN,NaN,NaN,NaN,NaN,NaN,32.0,20.0,0.0,NaN,https://vk.com/topic-33327655_26089874,2012-03-07,18:55
218,4,m2,NaN,NaN,NaN,NaN,NaN,NaN,9.0,5.0,0.0,0.0,https://vk.com/wall-33327655_2313,2014-11-25,23:24

In [109]:
ssmm_stream_elections_1_11.to_csv('ssmm_stream_elections_1_11.csv', sep='\t', encoding='utf-8', index=False)
ssmm_stream_elections_1_11.to_csv('../library: main/ssmm_elections_streams_1_11.csv', sep='\t', encoding='utf-8', index=False)

In [ ]:
'''
ПОПРАВИТЬ ssmm_elections_streams_1_11:
- пронумеровать анонсы (иначе дублируются по некоторым потокам)
+ добавить квоту, число заявок и число избранных
'''

In [ ]:
# добавить колонки: квота от потока, число заявок и число избранных

In [110]:
ssmm_elections_streams_1_11 = pd.read_csv('../library: main/ssmm_elections_streams_1_11.csv', sep='\t', encoding='utf-8')
ssmm_elections_streams_1_11 #.head()

,convocation_no,year_stream_no,year_no,stream_no,announcement_link,announcement_link_date,announcement_link_time,election_date,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,result_link,result_link_date,result_link_time
0,1,1.1,1.0,1.0,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,NaN,139.0,68.0,6.0,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
1,1,1.2,1.0,2.0,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,NaN,138.0,60.0,2.0,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
2,1,1.3,1.0,3.0,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,NaN,115.0,73.0,5.0,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55
3,1,2.1,2.0,1.0,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,NaN,133.0,91.0,5.0,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34
4,1,2.2,2.0,2.0,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,NaN,111.0,60.0,3.0,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,9,m2,2.0,0.0,https://vk.com/wall-33327655_8310,2019-10-22,1:46,2019-10-22,28.0,18.0,1.0,0.0,https://vk.com/wall-33327655_8372,2019-10-27,22:40
215,10,m2,2.0,0.0,https://vk.com/wall-33327655_9152,2020-10-30,10:32,2020-10-30,18.0,12.0,0.0,0.0,https://vk.com/wall-33327655_9310,2020-11-07,22:38
216,1,3.4,NaN,NaN,NaN,NaN,NaN,NaN,29.0,21.0,21.0,NaN,https://vk.com/topic-33327655_26089737,2012-03-07,2:03
217,1,4.4,NaN,NaN,NaN,NaN,NaN,NaN,32.0,20.0,0.0,NaN,https://vk.com/topic-33327655_26089874,2012-03-07,18:55
218,4,m2,NaN,NaN,NaN,NaN,NaN,NaN,9.0,5.0,0.0,0.0,https://vk.com/wall-33327655_2313,2014-11-25,23:24

In [25]:
ssmm_elections_candidates_1_11 = pd.read_csv('../library: main/ssmm_elections_candidates_1_11.csv', sep='\t', encoding='utf-8')
ssmm_elections_candidates_1_11.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
2,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
3,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
4,1_Семенов_Павел,Семенов Павел,1,1.2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,20.0,0,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00

In [26]:
counter_df = ssmm_elections_candidates_1_11.groupby(['convocation_no','year_stream_no']).agg({'conv_x_name':'count', 'elected_flg': 'sum'}).rename(columns={'conv_x_name':'applications_cnt', 'elected_flg':'elected_cnt'})
counter_df = counter_df.reset_index()
counter_df

     convocation_no year_stream_no  applications_cnt  elected_cnt
0                 1            1.1                 2            2
1                 1            1.2                 4            3
2                 1            1.3                 5            3
3                 1            2.1                 4            3
4                 1            2.2                 3            3
..              ...            ...               ...          ...
194              11            5.3                 3            3
195              11            5.4                 2            2
196              11            6.1                 2            2
197              11            6.3                 1            1
198              11             m1                 3            3

[199 rows x 4 columns]

In [94]:
# формула расчета квоты от потока

def def_quota(convocation_no, year_stream_no, stream_size):
    if convocation_no <= 5:
        if 'm' in year_stream_no:
            return 1
        elif int(year_stream_no[-1]) == 4:
            return 1
        else:
            return 3
    else:
        return min(stream_size//25 + 1, 3)
    
def_quota(6,'m1',30)

2

In [111]:
quota_df = ssmm_elections_streams_1_11[['convocation_no', 'year_stream_no', 'stream_size']]
quota_df['quota'] = quota_df.apply(lambda x: def_quota(x['convocation_no'], x['year_stream_no'], x['stream_size']), axis=1).astype(int)
quota_df

/var/folders/zh/mnvg84rj3_7413ycjzpn5y8r0000gp/T/ipykernel_11395/4028685463.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quota_df['quota'] = quota_df.apply(lambda x: def_quota(x['convocation_no'], x['year_stream_no'], x['stream_size']), axis=1).astype(int)

     convocation_no year_stream_no  stream_size  quota
0                 1            1.1        139.0      3
1                 1            1.2        138.0      3
2                 1            1.3        115.0      3
3                 1            2.1        133.0      3
4                 1            2.2        111.0      3
..              ...            ...          ...    ...
214               9             m2         28.0      2
215              10             m2         18.0      1
216               1            3.4         29.0      1
217               1            4.4         32.0      1
218               4             m2          9.0      1

[219 rows x 4 columns]

In [100]:
# WARNING: немного дублируются строки из-за двойных анонсов

ssmm_elections_streams_1_11[(ssmm_elections_streams_1_11['convocation_no'] == 6) & (ssmm_elections_streams_1_11['year_stream_no'] == '4.1')]

,convocation_no,year_stream_no,year_no,stream_no,announcement_link,announcement_link_date,announcement_link_time,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,result_link,result_link_date,result_link_time
106,6,4.1,4.0,1.0,https://vk.com/wall-33327655_5212,2016-10-20,0:51,95.0,50.0,0.0,2.0,https://vk.com/wall-33327655_5357,2016-10-31,23:50
107,6,4.1,4.0,1.0,https://vk.com/wall-33327655_5318,2016-10-26,22:45,95.0,50.0,0.0,2.0,https://vk.com/wall-33327655_5357,2016-10-31,23:50

In [112]:
full_df = quota_df.merge(counter_df,how='outer')
full_df['applications_cnt'] = full_df['applications_cnt'].fillna(0).astype(int)
full_df['elected_cnt'] = full_df['elected_cnt'].fillna(0).astype(int)
full_df = full_df.drop_duplicates()
full_df[60:120]

,convocation_no,year_stream_no,stream_size,quota,applications_cnt,elected_cnt
62,4,1.2,136.0,3,4,3
64,5,1.2,154.0,3,1,1
65,6,1.2,154.0,3,4,3
66,8,1.2,151.0,3,5,3
67,9,1.2,163.0,3,2,2
68,10,1.2,161.0,3,4,3
69,11,1.2,138.0,3,1,1
70,4,1.3,138.0,3,5,3
71,5,1.3,129.0,3,6,3
72,6,1.3,132.0,3,5,3
73,7,1.3,127.0,3,1,1
74,8,1.3,123.0,3,5,3
76,9,1.3,130.0,3,4,3
77,10,1.3,122.0,3,7,3
79,11,1.3,109.0,3,3,3
80,4,2.1,135.0,3,7,3
82,5,2.1,128.0,3,3,3
83,6,2.1,125.0,3,3,3
84,7,2.1,122.0,3,2,2
85,8,2.1,134.0,3,5,3
86,9,2.1,129.0,3,3,3
87,10,2.1,150.0,3,6,3
88,11,2.1,127.0,3,3,3
89,4,2.2,135.0,3,3,3
90,5,2.2,132.0,3,5,3
91,6,2.2,128.0,3,6,4
92,7,2.2,134.0,3,3,3
93,9,2.2,142.0,3,4,3
95,10,2.2,148.0,3,3,3
96,11,2.2,122.0,3,2,2
97,4,2.3,105.0,3,2,2
98,5,2.3,113.0,3,4,3
99,6,2.3,96.0,3,1,1
100,7,2.3,110.0,3,4,4
101,8,2.3,107.0,3,3,3
102,9,2.3,123.0,3,5,3
103,10,2.3,103.0,3,5,3
104,11,2.3,95.0,3,3,3
105,11,2.5,21.0,1,1,1
106,4,3.1,83.0,3,4,3
108,5,3.1,98.0,3,3,3
109,6,3.1,100.0,3,3,3
111,7,3.1,103.0,3,4,4
112,8,3.1,107.0,3,2,2
113,9,3.1,115.0,3,3,3
114,10,3.1,104.0,3,4,3
115,11,3.1,105.0,3,2,2
116,4,3.2,103.0,3,4,3
118,5,3.2,107.0,3,3,3
119,6,3.2,105.0,3,3,3
120,8,3.2,94.0,3,2,2
121,9,3.2,118.0,3,1,1
122,10,3.2,118.0,3,4,3
123,11,3.2,104.0,3,2,2
124,4,3.3,98.0,3,3,3
125,5,3.3,103.0,3,3,3
126,6,3.3,90.0,3,6,5
127,7,3.3,85.0,3,2,2
128,8,3.3,103.0,3,1,1
129,9,3.3,94.0,3,4,3

In [113]:
ssmm_elections_streams_1_11_upd = ssmm_elections_streams_1_11.merge(full_df, how='left')
ssmm_elections_streams_1_11_upd = ssmm_elections_streams_1_11_upd.sort_values(['convocation_no', 'year_stream_no', 'announcement_link_date'],
              ascending = [True,True,True]).reset_index().drop(['index'], axis=1)
ssmm_elections_streams_1_11_upd

,convocation_no,year_stream_no,year_no,stream_no,announcement_link,announcement_link_date,announcement_link_time,election_date,stream_size,voted_cnt,NOTA_cnt,invalid_cnt,result_link,result_link_date,result_link_time,quota,applications_cnt,elected_cnt
0,1,1.1,1.0,1.0,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,NaN,139.0,68.0,6.0,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55,3,2,2
1,1,1.2,1.0,2.0,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,NaN,138.0,60.0,2.0,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55,3,4,3
2,1,1.3,1.0,3.0,https://vk.com/topic-33327655_26089953,2012-02-26,0:16,NaN,115.0,73.0,5.0,NaN,https://vk.com/topic-33327655_26089953,2012-03-07,20:55,3,5,3
3,1,2.1,2.0,1.0,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,NaN,133.0,91.0,5.0,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34,3,4,3
4,1,2.2,2.0,2.0,https://vk.com/topic-33327655_26089854,2012-02-25,23:49,NaN,111.0,60.0,3.0,NaN,https://vk.com/topic-33327655_26089854,2012-02-28,22:34,3,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,11,5.3,5.0,3.0,https://vk.com/wall-33327655_9858,2021-10-05,10:35,2021-10-05,89.0,46.0,1.0,0.0,https://vk.com/wall-33327655_9912,2021-10-12,20:20,3,3,3
215,11,5.4,5.0,4.0,https://vk.com/wall-33327655_9853,2021-10-04,10:47,2021-10-04,37.0,21.0,0.0,0.0,https://vk.com/wall-33327655_9878,2021-10-06,20:36,2,2,2
216,11,6.1,6.0,1.0,https://vk.com/wall-33327655_9978,2021-10-16,10:25,2021-10-16,87.0,44.0,6.0,0.0,https://vk.com/wall-33327655_10026,2021-10-21,15:44,3,2,2
217,11,6.3,6.0,3.0,https://vk.com/wall-33327655_9982,2021-10-16,10:50,2021-10-16,93.0,47.0,3.0,0.0,https://vk.com/wall-33327655_10031,2021-10-21,22:02,3,1,1
218,11,m1,1.0,0.0,https://vk.com/wall-33327655_9983,2021-10-16,11:20,2021-10-16,51.0,26.0,3.0,0.0,https://vk.com/wall-33327655_10018,2021-10-20,20:21,3,3,3

In [114]:
ssmm_elections_streams_1_11_upd.to_csv('ssmm_stream_elections_1_11.csv', sep='\t', encoding='utf-8', index=False)
ssmm_elections_streams_1_11_upd.to_csv('../library: main/ssmm_elections_streams_1_11.csv', sep='\t', encoding='utf-8', index=False)

# ПРОВЕРКИ

In [ ]:
# СЫМИТИРОВАТЬ ВЫЯВЛЕНИЕ ИЗБИРАЕМЫХ КАНДИДАТОВ 
# (все кандидаты с голосами не менее чем у кандидата на N месте, где N = quota)

In [30]:
# https://stackoverflow.com/questions/37482733/selecting-top-n-elements-from-each-group-in-pandas-groupby

select_number = full_df[['convocation_no','year_stream_no','quota']]
select_number.set_index(['convocation_no','year_stream_no'], inplace=True)

d = select_number.to_dict()
d1 = d['quota']
# print(d1)

# во 2 и 3 созывах неизвестны votes_cnt, поэтому исключить
temp_df = ssmm_elections_candidates_1_11[~ssmm_elections_candidates_1_11['convocation_no'].isin([2,3])]

imitate_elected_df = temp_df.groupby(['convocation_no','year_stream_no']).apply(lambda x: x.nlargest(d1[x.name],'votes_cnt', keep='all')).reset_index(drop=True)
imitate_elected_df #.head(11)

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm
0,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
1,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
2,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
3,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
4,1_Кузнецова_Алёна,Кузнецова Алёна,1,1.2,112.0,"""Меня очень интересует жизнь Университета. я б...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,28.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,11_Терехов_Михаил_Сергеевич,Терехов Михаил Сергеевич,11,6.1,602.0,За правду!,https://vk.com/wall-33327655_9978,2021-10-16 10:25:00,16.0,1,https://vk.com/wall-33327655_10026,2021-10-21 15:44:00,2021-10-16 10:25:00
362,11_Поликарпов_Александр_Валерьевич,Поликарпов Александр Валерьевич,11,6.3,621.0,Был одним из основателей бегового клуба MSU RU...,https://vk.com/wall-33327655_9982,2021-10-16 10:50:00,43.0,1,https://vk.com/wall-33327655_10031,2021-10-21 22:02:00,2021-10-16 10:50:00
363,11_Третьякова_Екатерина_Алексеевна,Третьякова Екатерина Алексеевна,11,m1,NaN,Я как человек с немалым опытом в делах организ...,https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,19.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
364,11_Маммагаджиев_Руслан_Гаджимагомедович,Маммагаджиев Руслан Гаджимагомедович,11,m1,NaN,Долгое время был пикчером профкома мехмата. Се...,https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,10.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
365,11_Каляев_Тимур_Джанбулатович,Каляев Тимур Джанбулатович,11,m1,NaN,"Всем привет! Я только недавно на мехмате, но х...",https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,6.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00

In [31]:
official_elected_df = temp_df[temp_df['elected_flg'] == 1]
official_elected_df

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
2,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
3,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
5,1_Кузнецова_Алёна,Кузнецова Алёна,1,1.2,112.0,"""Меня очень интересует жизнь Университета. я б...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,28.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,11_Каляев_Тимур_Джанбулатович,Каляев Тимур Джанбулатович,11,m1,NaN,"Всем привет! Я только недавно на мехмате, но х...",https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,6.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
519,11_Маммагаджиев_Руслан_Гаджимагомедович,Маммагаджиев Руслан Гаджимагомедович,11,m1,NaN,Долгое время был пикчером профкома мехмата. Се...,https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,10.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
520,11_Третьякова_Екатерина_Алексеевна,Третьякова Екатерина Алексеевна,11,m1,NaN,Я как человек с немалым опытом в делах организ...,https://vk.com/wall-33327655_9983,2021-10-16 11:20:00,19.0,1,https://vk.com/wall-33327655_10018,2021-10-20 20:21:00,2021-10-16 11:20:00
521,1_Федорова_Елена_Игоревна,Федорова Елена Игоревна,1,4.4,NaN,NaN,NaN,NaN,20.0,1,https://vk.com/topic-33327655_26089874,2012-03-07 18:55:00,2012-03-07 18:55:00
523,4_Вергазов_Марат_Марсович,Вергазов Марат Марсович,4,m2,NaN,NaN,NaN,NaN,5.0,1,https://vk.com/wall-33327655_2313,2014-11-25 23:24:00,2014-11-25 23:24:00

In [32]:
official_elected_df[~official_elected_df['conv_x_name'].isin(imitate_elected_df['conv_x_name'])]

# всё ок

Empty DataFrame
Columns: [conv_x_name, name, convocation_no, year_stream_no, academic_group_no, program_txt, announcement_link, announcement_dttm, votes_cnt, elected_flg, result_link, result_dttm, appearance_dttm]
Index: []

In [15]:
def levenshtein(s1, s2):
    if len(s1) < len(s2):
        return levenshtein(s2, s1)

    # len(s1) >= len(s2)
    if len(s2) == 0:
        return len(s1)

    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1 # j+1 instead of j since previous_row and current_row are one character longer
            deletions = current_row[j] + 1       # than s2
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row
    
    return previous_row[-1]

string1 = "abc"
string2 = "aef"

print(levenshtein(string1, string2))

2

In [119]:
names = list(candidates_conv_1_11_upd['name']) + list(temp_votes_conv_1_3['name']) + list(final_votes_conv_4_11['name'])

from collections import Counter

names_stat = Counter(names) #.most_common()
# names_stat

# names_uniq = list(set(names))
# names_uniq

In [120]:
# выявляем похожие имена, чтобы потом заменить РУКАМИ

for a in names_stat.keys():
    for b in names_stat.keys():
        if a != b and levenshtein(a, b) <= 4 and names_stat[a] >= names_stat[b]:
            print(levenshtein(a, b), ' - ', a, names_stat[a], ' : ', names_stat[b], b)

In [121]:
# выявляем имена без отчества, чтобы потом заменить РУКАМИ

for a in names_stat.keys():
    for b in names_stat.keys():
        if len(a) > len(b) and levenshtein(a[:len(b)], b) <= 4:
            print(a, names_stat[a], ' : ', names_stat[b], b)

Семенюк Павел Игоревич 4  :  2 Семенов Павел
Белан Андрей Владимирович 2  :  2 Левин Андрей

In [42]:
# выявляем имена с перепутанными отчествами, чтобы потом заменить РУКАМИ

for a in names_stat.keys():
    for b in names_stat.keys():
        if a != b and levenshtein(a[:12], b[:12]) <= 2 and names_stat[a] >= names_stat[b]:
            print(a, names_stat[a], ' : ', names_stat[b], b)

Коновалов Антон Александрович 2  :  1 Коновалов Дмитрий Игоревич
Семенюк Павел Игоревич 2  :  1 Семенов Павел
Порфирьева Наталия Алексеевна 1  :  1 Перфильева Нелли Андреевна
Федотов Константин Алексеевич 1  :  1 Фёдоров Константин Дмитриевич
Алиев Рамиль Камиль Оглы 1  :  1 Алеев Дамиль Павлович
Перфильева Нелли Андреевна 1  :  1 Порфирьева Наталия Алексеевна
Фёдоров Константин Дмитриевич 1  :  1 Федотов Константин Алексеевич
Третьяков Пётр Максимович 3  :  2 Третьяков Артём Алексеевич
Саметов Максим Алексеевич 2  :  1 Савелов Максим Павлович
Лобанова Алёна Валерьевна 3  :  1 Лобанова Анастасия Алексеевна
Алеев Дамиль Павлович 1  :  1 Алиев Рамиль Камиль Оглы