In [ ]:
'''
tables for Tableau dashboards:

1. ssmm_candidates_core.csv - full info about every candidate from first elections to honorary status 
2. ssmm_full_applications.csv - full info about every application
- ПРОБЛЕМА С ПЕРЕНОСОМ АБЗАЦЕВ В ТЕКСТЕ ПРОГРАММ?
3. ssmm_full_management.csv - full info about management positions 

'''

In [52]:
from datetime import datetime, date, time

techical_dict = {}
techical_dict['conv_x_name'] = '0_Technical_string'
techical_dict['name'] = 'STRING'
techical_dict['convocation_no'] = 0
techical_dict['year_stream_no'] = 'STRING'
techical_dict['academic_group_no'] = 0
techical_dict['announcement_link'] = 'STRING'
techical_dict['announcement_dttm'] = datetime(2000, 1, 1, 1, 1)
techical_dict['votes_cnt'] = 0
techical_dict['elected_flg'] = 0
techical_dict['result_link'] = 'STRING'
techical_dict['result_dttm'] = datetime(2000, 1, 1, 1, 1)
techical_dict['appearance_dttm'] = datetime(2000, 1, 1, 1, 1)
techical_dict['classic_year_no'] = 'STRING'
techical_dict['year_no'] = 0
techical_dict['stream_no'] = 0
techical_dict['course_level'] = 'STRING'
techical_dict['specialization'] = 'STRING'
techical_dict['short_specialization'] = 'STRING'
techical_dict['year'] = 0
techical_dict['graduated_flg'] = 0
techical_dict['program_txt'] = 'STRING'
techical_dict['program_symbols_cnt'] = 0
techical_dict['program_symbols_without_spaces_cnt'] = 0
techical_dict['program_words_cnt'] = 0
techical_dict['program_avg_word_length'] = 0
techical_dict['cultmass_flg'] = 0
techical_dict['education_flg'] = 0
techical_dict['egoistic_flg'] = 0
techical_dict['grants_flg'] = 0
techical_dict['inform_flg'] = 0
techical_dict['infrastructure_flg'] = 0
techical_dict['partners_flg'] = 0
techical_dict['rights_flg'] = 0
techical_dict['sport_flg'] = 0
techical_dict['university_level_flg'] = 0
techical_dict['nothing_flg'] = 0
techical_dict['academic_year'] = 'STRING'

techical_dict['ssmm_id'] = 0
techical_dict['name'] = 'STRING'
techical_dict['first_appearance_dttm'] = datetime(2000, 1, 1, 1, 1)
techical_dict['last_appearance_dttm'] = datetime(2000, 1, 1, 1, 1)
techical_dict['member_id'] = 0
techical_dict['first_result_dttm'] = datetime(2000, 1, 1, 1, 1)
techical_dict['elected_flg'] = 0
techical_dict['min_member_conv_no'] = 0
techical_dict['max_member_conv_no'] = 0
techical_dict['member_conv_list'] = 'STRING'
techical_dict['member_conv_cnt'] = 0
techical_dict['min_cand_conv_no'] = 0
techical_dict['max_cand_conv_no'] = 0
techical_dict['cand_conv_list'] = 'STRING'
techical_dict['cand_conv_cnt'] = 0
techical_dict['first_app_year_stream_no'] = 'STRING'
techical_dict['last_app_year_stream_no'] = 'STRING'
techical_dict['conv_1'] = 'STRING'
techical_dict['conv_2'] = 'STRING'
techical_dict['conv_3'] = 'STRING'
techical_dict['conv_4'] = 'STRING'
techical_dict['conv_5'] = 'STRING'
techical_dict['conv_6'] = 'STRING'
techical_dict['conv_7'] = 'STRING'
techical_dict['conv_8'] = 'STRING'
techical_dict['conv_9'] = 'STRING'
techical_dict['conv_10'] = 'STRING'
techical_dict['conv_11'] = 'STRING'
techical_dict['manage_min_convocation_no'] = 0
techical_dict['manage_max_convocation_no'] = 0
techical_dict['manage_convocation_list'] = 'STRING'
techical_dict['manage_convocation_cnt'] = 0
techical_dict['position_list'] = 'STRING'
techical_dict['position_cnt'] = 0
techical_dict['honorary_award_date'] = datetime(2000, 1, 1)
techical_dict['honorary_flg'] = 0
techical_dict['gender'] = 'STRING'

In [15]:
import pandas as pd
# import numpy as np

# 1. Candidate core table

In [3]:
ssmm_candidates_core = pd.read_csv('../library: main/ssmm_candidates_core.csv', sep='\t', encoding='utf-8')
ssmm_candidates_core.head()

,ssmm_id,name,first_appearance_dttm,last_appearance_dttm,member_id,first_result_dttm,elected_flg,min_member_conv_no,max_member_conv_no,member_conv_list,...,conv_11,manage_min_convocation_no,manage_max_convocation_no,manage_convocation_list,manage_convocation_cnt,position_list,position_cnt,honorary_award_date,honorary_flg,gender
0,1,Владыкина Вероника Евгеньевна,2012-02-25 23:16:00,2013-11-17 14:21:00,10.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,2.0,"[1, 2]",2.0,['Второй заместитель представителей в Студсове...,3.0,2014-11-29,1,female
1,2,Коновалов Антон Александрович,2012-02-25 23:16:00,2012-11-04 23:03:00,11.0,2012-03-07 02:03:00,1,1.0,2.0,"[1, 2]",...,NaN,1.0,1.0,[1],1.0,['Координатор РГ «Трудоустройство»'],1.0,NaN,0,male
2,3,Ласкин Алексей Александрович,2012-02-25 23:16:00,2013-11-17 14:21:00,12.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 3]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
3,4,Малхасян Арамаис,2012-02-25 23:16:00,2012-02-25 23:16:00,13.0,2012-03-07 02:03:00,1,1.0,1.0,[1],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
4,5,Попов Леонид Андреевич,2012-02-25 23:16:00,2013-11-17 14:21:00,14.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,2.0,"[1, 2]",2.0,"['Заместитель председателя', 'Координатор РГ «...",2.0,2014-11-29,1,male

In [53]:
# добавить техническую строчку для задания типов полей

list_of_columns = list(ssmm_candidates_core)
# list_of_columns

techical_dict_applications = {}

for key in list_of_columns:
    techical_dict_applications[key] = techical_dict[key]

# pd.DataFrame(techical_dict.items())
techical_df = pd.DataFrame([techical_dict_applications])
techical_df

,ssmm_id,name,first_appearance_dttm,last_appearance_dttm,member_id,first_result_dttm,elected_flg,min_member_conv_no,max_member_conv_no,member_conv_list,...,conv_11,manage_min_convocation_no,manage_max_convocation_no,manage_convocation_list,manage_convocation_cnt,position_list,position_cnt,honorary_award_date,honorary_flg,gender
0,0,STRING,2000-01-01 01:01:00,2000-01-01 01:01:00,0,2000-01-01 01:01:00,0,0,0,STRING,...,STRING,0,0,STRING,0,STRING,0,2000-01-01,0,STRING

In [56]:
ssmm_candidates_core_2 = pd.concat([techical_df,ssmm_candidates_core])
ssmm_candidates_core_2.head(10)

,ssmm_id,name,first_appearance_dttm,last_appearance_dttm,member_id,first_result_dttm,elected_flg,min_member_conv_no,max_member_conv_no,member_conv_list,...,conv_11,manage_min_convocation_no,manage_max_convocation_no,manage_convocation_list,manage_convocation_cnt,position_list,position_cnt,honorary_award_date,honorary_flg,gender
0,0,STRING,2000-01-01 01:01:00,2000-01-01 01:01:00,0.0,2000-01-01 01:01:00,0,0.0,0.0,STRING,...,STRING,0.0,0.0,STRING,0.0,STRING,0.0,2000-01-01 00:00:00,0,STRING
0,1,Владыкина Вероника Евгеньевна,2012-02-25 23:16:00,2013-11-17 14:21:00,10.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,2.0,"[1, 2]",2.0,['Второй заместитель представителей в Студсове...,3.0,2014-11-29,1,female
1,2,Коновалов Антон Александрович,2012-02-25 23:16:00,2012-11-04 23:03:00,11.0,2012-03-07 02:03:00,1,1.0,2.0,"[1, 2]",...,NaN,1.0,1.0,[1],1.0,['Координатор РГ «Трудоустройство»'],1.0,NaN,0,male
2,3,Ласкин Алексей Александрович,2012-02-25 23:16:00,2013-11-17 14:21:00,12.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 3]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
3,4,Малхасян Арамаис,2012-02-25 23:16:00,2012-02-25 23:16:00,13.0,2012-03-07 02:03:00,1,1.0,1.0,[1],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
4,5,Попов Леонид Андреевич,2012-02-25 23:16:00,2013-11-17 14:21:00,14.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,2.0,"[1, 2]",2.0,"['Заместитель председателя', 'Координатор РГ «...",2.0,2014-11-29,1,male
5,6,Самонов Алексей Александрович,2012-02-25 23:16:00,2013-11-17 14:21:00,15.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 3]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
6,7,Сапунов Кирилл Вячеславович,2012-02-25 23:16:00,2013-11-17 14:21:00,16.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,3.0,"[1, 2, 3]",3.0,"['Первый представитель в Студсовете МГУ', 'Коо...",4.0,2014-11-29,1,male
7,8,Тропин Александр Михайлович,2012-02-25 23:16:00,2016-10-23 20:18:00,17.0,2012-03-07 02:03:00,1,1.0,6.0,"[1, 2, 6]",...,NaN,1.0,2.0,"[1, 2]",2.0,['Координатор РГ «Разработка Устава и Положени...,4.0,2014-11-29,1,male
8,9,Аканаев Тимур Рашитович,2012-02-25 23:49:00,2012-02-25 23:49:00,1.0,2012-02-28 22:34:00,1,1.0,1.0,[1],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male

In [59]:
ssmm_candidates_core_2[ssmm_candidates_core_2['name'] == 'Тропин Александр Михайлович']['conv_6']
ssmm_candidates_core_2[['name','conv_6']].head(20)

                             name  conv_6
0                          STRING  STRING
0   Владыкина Вероника Евгеньевна     NaN
1   Коновалов Антон Александрович     NaN
2    Ласкин Алексей Александрович     NaN
3                Малхасян Арамаис     NaN
4          Попов Леонид Андреевич     NaN
5   Самонов Алексей Александрович     NaN
6     Сапунов Кирилл Вячеславович     NaN
7     Тропин Александр Михайлович      m1
8         Аканаев Тимур Рашитович     NaN
9       Асташов Дмитрий Сергеевич     NaN
10      Валиев Зураб Владимирович     NaN
11       Гильманов Роман Павлович     NaN
12         Глухова Алёна Олеговна     NaN
13  Костицын Александр Алексеевич     NaN
14     Матвеев Алексей Викторович     NaN
15  Оджаев Рахмет Курбандурдыевич     NaN
16       Осин Руслан Владимирович     NaN
17    Харлашин Владимир Сергеевич     NaN
18    Шариков Алексей Анатольевич     NaN

In [55]:
ssmm_candidates_core_2.to_csv('ssmm_candidates_core.csv', sep='\t', encoding='utf-8', index=False)

# 2. Applications table

In [6]:
ssmm_elections_candidates_1_11 = pd.read_csv('../library: main/ssmm_elections_candidates_1_11.csv', sep='\t', encoding='utf-8')
ssmm_elections_candidates_1_11.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
2,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
3,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
4,1_Семенов_Павел,Семенов Павел,1,1.2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,20.0,0,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00

In [32]:
ssmm_dict_year_stream = pd.read_csv('../dictionaries/ssmm_dict_year_stream.csv', sep='\t', encoding='utf-8')
# ssmm_dict_year_stream.head()
ssmm_dict_graduated_years = pd.read_csv('../dictionaries/ssmm_dict_graduated_years.csv', sep='\t', encoding='utf-8')
# ssmm_dict_year_stream.head()
ssmm_dict_convocations = pd.read_csv('../dictionaries/ssmm_dict_convocations.csv', sep='\t', encoding='utf-8')
# ssmm_dict_convocations.head()

In [61]:
ys_df = ssmm_elections_candidates_1_11.merge(ssmm_dict_year_stream)
ys_df = ys_df.merge(ssmm_dict_graduated_years)
ys_df['program_txt_2'] = ys_df['program_txt']
ys_df = ys_df.drop(['program_txt'], axis=1).rename(columns={'program_txt_2':'program_txt'})
ys_df.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,appearance_dttm,classic_year_no,year_no,stream_no,course_level,specialization,short_specialization,year,graduated_flg,program_txt
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,...,2012-02-26 00:16:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,Активный участник и организатор различных меро...
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,...,2012-02-26 00:16:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,NaN
2,2_Остроухова_Наталья_Владимировна,Остроухова Наталья Владимировна,2,1.1,101.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,Мне всегда была интересна общественная работа ...
3,2_Николаева_Наталия_Михайловна,Николаева Наталия Михайловна,2,1.1,102.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,0,NaN,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,NaN
4,2_Габидов_Александр_Сергеевич,Габидов Александр Сергеевич,2,1.1,104.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,"Я хотел бы вступить в Студенческий Совет, чтоб..."

In [62]:
ys_df = ys_df.replace(r'\n', ' / ', regex=True) 
ys_df 
# .head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,appearance_dttm,classic_year_no,year_no,stream_no,course_level,specialization,short_specialization,year,graduated_flg,program_txt
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,...,2012-02-26 00:16:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,Активный участник и организатор различных меро...
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,...,2012-02-26 00:16:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,NaN
2,2_Остроухова_Наталья_Владимировна,Остроухова Наталья Владимировна,2,1.1,101.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,Мне всегда была интересна общественная работа ...
3,2_Николаева_Наталия_Михайловна,Николаева Наталия Михайловна,2,1.1,102.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,0,NaN,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,NaN
4,2_Габидов_Александр_Сергеевич,Габидов Александр Сергеевич,2,1.1,104.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,"Я хотел бы вступить в Студенческий Совет, чтоб..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,11_Мазитова_Вероника_Рустэмовна,Мазитова Вероника Рустэмовна,11,6.1,606.0,https://vk.com/wall-33327655_9978,2021-10-16 10:25:00,27.0,1,https://vk.com/wall-33327655_10026,...,2021-10-16 10:25:00,6,6,1,Старшие курсы,Фундаментальная математика,Математика,2021,1,"Всем привет! Попав в студенческий совет, покин..."
520,11_Терехов_Михаил_Сергеевич,Терехов Михаил Сергеевич,11,6.1,602.0,https://vk.com/wall-33327655_9978,2021-10-16 10:25:00,16.0,1,https://vk.com/wall-33327655_10026,...,2021-10-16 10:25:00,6,6,1,Старшие курсы,Фундаментальная математика,Математика,2021,1,За правду!
521,11_Водолеев_Марк_Дмитриевич,Водолеев Марк Дмитриевич,11,3.5,341.0,https://vk.com/wall-33327655_9887,2021-10-08 11:23:00,3.0,0,https://vk.com/wall-33327655_9906,...,2021-10-08 11:23:00,3,3,5,Старшие курсы,Фундаментальная математика и математическая фи...,ФММФ,2021,0,"Меня зовут Марк Водолеев, и я уже больше года ..."
522,11_Лоншаков_Никита_Артемович,Лоншаков Никита Артемович,11,3.5,341.0,https://vk.com/wall-33327655_9887,2021-10-08 11:23:00,5.0,1,https://vk.com/wall-33327655_9906,...,2021-10-08 11:23:00,3,3,5,Старшие курсы,Фундаментальная математика и математическая фи...,ФММФ,2021,0,Привет! В предыдущем учебного году мне выдалас...
523,11_Янушкевич_Иван_Михайлович,Янушкевич Иван Михайлович,11,2.5,241.0,https://vk.com/wall-33327655_9900,2021-10-12 10:10:00,11.0,1,https://vk.com/wall-33327655_9984,...,2021-10-12 10:10:00,2,2,5,Младшие курсы,Фундаментальная математика и математическая фи...,ФММФ,2021,0,Привет! / В Студенческом Совете планирую заним...

In [28]:
ssmm_programs_info_conv_1_11 = pd.read_csv('../library: main/ssmm_programs_info_conv_1_11.csv', sep='\t', encoding='utf-8')
ssmm_programs_info_conv_1_11.head()

,conv_x_name,program_txt,program_symbols_cnt,program_symbols_without_spaces_cnt,program_words_cnt,program_avg_word_length,cultmass_flg,education_flg,egoistic_flg,grants_flg,inform_flg,infrastructure_flg,partners_flg,rights_flg,sport_flg,university_level_flg,nothing_flg
0,1_Левин_Андрей,Активный участник и организатор различных меро...,138,122,17,7.176471,1,0,0,0,0,0,0,0,0,0,0
1,1_Кириллова_Полина,Мне нравится заниматься общественной деятельно...,2306,1981,322,6.152174,1,0,0,0,0,1,0,0,1,0,0
2,1_Семенов_Павел,"""Здравствуйте. Я так понимаю, что я уже поздно...",1175,1008,168,6.000000,0,0,0,0,0,1,0,1,0,0,0
3,1_Кузнецова_Алёна,"""Меня очень интересует жизнь Университета. я б...",339,295,45,6.555556,1,0,0,0,0,0,0,0,0,0,0
4,1_Кунденко_Вадим,""" Добрый день! Пару слов о себе. Путь к мехм...",971,822,147,5.591837,0,0,1,0,0,0,0,1,0,0,0

In [63]:
pr_df = ssmm_programs_info_conv_1_11.drop(['program_txt'], axis=1)

ys_df = ys_df.merge(pr_df, left_on='conv_x_name', right_on='conv_x_name', how='outer')
ys_df.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,education_flg,egoistic_flg,grants_flg,inform_flg,infrastructure_flg,partners_flg,rights_flg,sport_flg,university_level_flg,nothing_flg
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2_Остроухова_Наталья_Владимировна,Остроухова Наталья Владимировна,2,1.1,101.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2_Николаева_Наталия_Михайловна,Николаева Наталия Михайловна,2,1.1,102.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2_Габидов_Александр_Сергеевич,Габидов Александр Сергеевич,2,1.1,104.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [64]:
ys_df = ys_df.merge(ssmm_dict_convocations[['convocation_no','academic_year']], left_on='convocation_no', right_on='convocation_no', how='outer')
ys_df = ys_df.merge(ssmm_candidates_core[['name','gender']], left_on='name', right_on='name', how='outer')
ys_df.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,grants_flg,inform_flg,infrastructure_flg,partners_flg,rights_flg,sport_flg,university_level_flg,nothing_flg,academic_year,gender
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011/2012,male
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011/2012,male
2,2_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,2,2.1,201.0,https://vk.com/topic-33327655_27333032,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012/2013,male
3,3_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,3,3.1,302.0,https://vk.com/topic-33327655_29117864,2013-11-17 14:31:00,NaN,1,https://vk.com/wall-33327655_1600,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2013/2014,male
4,4_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,4,4.1,402.0,https://vk.com/wall-33327655_2210,2014-11-16 21:54:00,45.0,1,https://vk.com/wall-33327655_2240,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2014/2015,male

In [65]:
# добавить техническую строчку для задания типов полей

list_of_columns = list(ys_df)
techical_dict_applications = {}

for key in list_of_columns:
    techical_dict_applications[key] = techical_dict[key]

# pd.DataFrame(techical_dict.items())
techical_df = pd.DataFrame([techical_dict_applications])
techical_df

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,grants_flg,inform_flg,infrastructure_flg,partners_flg,rights_flg,sport_flg,university_level_flg,nothing_flg,academic_year,gender
0,0_Technical_string,STRING,0,STRING,0,STRING,2000-01-01 01:01:00,0,0,STRING,...,0,0,0,0,0,0,0,0,STRING,STRING

In [66]:
ys_df_2 = pd.concat([techical_df,ys_df])
ys_df_2.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,grants_flg,inform_flg,infrastructure_flg,partners_flg,rights_flg,sport_flg,university_level_flg,nothing_flg,academic_year,gender
0,0_Technical_string,STRING,0,STRING,0.0,STRING,2000-01-01 01:01:00,0.0,0,STRING,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,STRING,STRING
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2011/2012,male
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011/2012,male
2,2_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,2,2.1,201.0,https://vk.com/topic-33327655_27333032,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012/2013,male
3,3_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,3,3.1,302.0,https://vk.com/topic-33327655_29117864,2013-11-17 14:31:00,NaN,1,https://vk.com/wall-33327655_1600,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2013/2014,male

In [67]:
ys_df_2.to_csv('ssmm_full_applications.csv', sep='\t', encoding='utf-8', index=False)

# 3. Management table

In [5]:
ssmm_full_management_1_11 = pd.read_csv('../library: main/ssmm_full_management_1_11.csv', sep='\t', encoding='utf-8')
ssmm_full_management_1_11.head()

,convocation_no,position,name,position_short,position_type,working_group_name,short_working_group_name,constant_flg,MSU_council_member_flg,vice_flg
0,1,Второй заместитель представителей в Студсовете...,Владыкина Вероника Евгеньевна,Заместитель представителей в Студсовете МГУ,Представительская должность,NaN,NaN,NaN,0.0,1.0
1,1,Второй представитель в Студсовете МГУ,Савушкин Никита Максимович,Представитель в Студсовете МГУ,Представительская должность,NaN,NaN,NaN,1.0,0.0
2,1,Заместитель председателя,Асташов Дмитрий Сергеевич,Заместитель председателя,Руководящая должность,NaN,NaN,NaN,0.0,1.0
3,1,Координатор РГ «Бытовые вопросы»,Котляров Никита Владимирович,Координатор,Руководящая должность,Бытовые вопросы,Бытовые вопросы,1.0,NaN,NaN
4,1,Координатор РГ «Образование»,Владыкина Вероника Евгеньевна,Координатор,Руководящая должность,Образование,Образование,1.0,NaN,NaN

In [35]:
temp_df = ssmm_full_management_1_11.merge(ys_df, left_on =['convocation_no','name'], right_on =['convocation_no','name'], how='left')
temp_df.head()

,convocation_no,position,name,position_short,position_type,working_group_name,short_working_group_name,constant_flg,MSU_council_member_flg,vice_flg,...,egoistic_flg,grants_flg,inform_flg,infrastructure_flg,partners_flg,rights_flg,sport_flg,university_level_flg,nothing_flg,academic_year
0,1,Второй заместитель представителей в Студсовете...,Владыкина Вероника Евгеньевна,Заместитель представителей в Студсовете МГУ,Представительская должность,NaN,NaN,NaN,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2011/2012
1,1,Второй представитель в Студсовете МГУ,Савушкин Никита Максимович,Представитель в Студсовете МГУ,Представительская должность,NaN,NaN,NaN,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2011/2012
2,1,Заместитель председателя,Асташов Дмитрий Сергеевич,Заместитель председателя,Руководящая должность,NaN,NaN,NaN,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2011/2012
3,1,Координатор РГ «Бытовые вопросы»,Котляров Никита Владимирович,Координатор,Руководящая должность,Бытовые вопросы,Бытовые вопросы,1.0,NaN,NaN,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,2011/2012
4,1,Координатор РГ «Образование»,Владыкина Вероника Евгеньевна,Координатор,Руководящая должность,Образование,Образование,1.0,NaN,NaN,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2011/2012

In [36]:
temp_df.to_csv('ssmm_full_management.csv', sep='\t', encoding='utf-8', index=False)