In [ ]:
'''
tables for Tableau dashboards:

1. ssmm_candidates_core.csv - full info about every candidate from first elections to honorary status 
2. ssmm_full_applications.csv - full info about every application
- ПРОБЛЕМА С ПЕРЕНОСОМ АБЗАЦЕВ В ТЕКСТЕ ПРОГРАММ?
3. ssmm_full_management.csv - full info about management positions 

'''

In [15]:
import pandas as pd
# import numpy as np

# 1. Candidate core table

In [3]:
ssmm_candidates_core = pd.read_csv('../library: main/ssmm_candidates_core.csv', sep='\t', encoding='utf-8')
ssmm_candidates_core.head()

,ssmm_id,name,first_appearance_dttm,last_appearance_dttm,member_id,first_result_dttm,elected_flg,min_member_conv_no,max_member_conv_no,member_conv_list,...,conv_11,manage_min_convocation_no,manage_max_convocation_no,manage_convocation_list,manage_convocation_cnt,position_list,position_cnt,honorary_award_date,honorary_flg,gender
0,1,Владыкина Вероника Евгеньевна,2012-02-25 23:16:00,2013-11-17 14:21:00,10.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,2.0,"[1, 2]",2.0,['Второй заместитель представителей в Студсове...,3.0,2014-11-29,1,female
1,2,Коновалов Антон Александрович,2012-02-25 23:16:00,2012-11-04 23:03:00,11.0,2012-03-07 02:03:00,1,1.0,2.0,"[1, 2]",...,NaN,1.0,1.0,[1],1.0,['Координатор РГ «Трудоустройство»'],1.0,NaN,0,male
2,3,Ласкин Алексей Александрович,2012-02-25 23:16:00,2013-11-17 14:21:00,12.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 3]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
3,4,Малхасян Арамаис,2012-02-25 23:16:00,2012-02-25 23:16:00,13.0,2012-03-07 02:03:00,1,1.0,1.0,[1],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,male
4,5,Попов Леонид Андреевич,2012-02-25 23:16:00,2013-11-17 14:21:00,14.0,2012-03-07 02:03:00,1,1.0,3.0,"[1, 2, 3]",...,NaN,1.0,2.0,"[1, 2]",2.0,"['Заместитель председателя', 'Координатор РГ «...",2.0,2014-11-29,1,male

In [4]:
ssmm_candidates_core.to_csv('ssmm_candidates_core.csv', sep='\t', encoding='utf-8', index=False)

# 2. Applications table

In [6]:
ssmm_elections_candidates_1_11 = pd.read_csv('../library: main/ssmm_elections_candidates_1_11.csv', sep='\t', encoding='utf-8')
ssmm_elections_candidates_1_11.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,program_txt,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,result_dttm,appearance_dttm
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,Активный участник и организатор различных меро...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
2,1_Власов_Артем_Андреевич,Власов Артем Андреевич,1,1.2,107.0,NaN,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,36.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
3,1_Кириллова_Полина,Кириллова Полина,1,1.2,112.0,Мне нравится заниматься общественной деятельно...,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,40.0,1,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00
4,1_Семенов_Павел,Семенов Павел,1,1.2,112.0,"""Здравствуйте. Я так понимаю, что я уже поздно...",https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,20.0,0,https://vk.com/topic-33327655_26089953,2012-03-07 20:55:00,2012-02-26 00:16:00

In [10]:
ssmm_dict_year_stream = pd.read_csv('../dictionaries/ssmm_dict_year_stream.csv', sep='\t', encoding='utf-8')
# ssmm_dict_year_stream.head()
ssmm_dict_graduated_years = pd.read_csv('../dictionaries/ssmm_dict_graduated_years.csv', sep='\t', encoding='utf-8')
# ssmm_dict_year_stream.head()

In [16]:
ys_df = ssmm_elections_candidates_1_11.merge(ssmm_dict_year_stream)
ys_df = ys_df.merge(ssmm_dict_graduated_years)
ys_df['program_txt_2'] = ys_df['program_txt']
ys_df = ys_df.drop(['program_txt'], axis=1).rename(columns={'program_txt_2':'program_txt'})
ys_df.head()

,conv_x_name,name,convocation_no,year_stream_no,academic_group_no,announcement_link,announcement_dttm,votes_cnt,elected_flg,result_link,...,appearance_dttm,classic_year_no,year_no,stream_no,course_level,specialization,short_specialization,year,graduated_flg,program_txt
0,1_Левин_Андрей,Левин Андрей,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,48.0,1,https://vk.com/topic-33327655_26089953,...,2012-02-26 00:16:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,Активный участник и организатор различных меро...
1,1_Матвеев_Дмитрий_Александрович,Матвеев Дмитрий Александрович,1,1.1,101.0,https://vk.com/topic-33327655_26089953,2012-02-26 00:16:00,49.0,1,https://vk.com/topic-33327655_26089953,...,2012-02-26 00:16:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,NaN
2,2_Остроухова_Наталья_Владимировна,Остроухова Наталья Владимировна,2,1.1,101.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,Мне всегда была интересна общественная работа ...
3,2_Николаева_Наталия_Михайловна,Николаева Наталия Михайловна,2,1.1,102.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,0,NaN,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,NaN
4,2_Габидов_Александр_Сергеевич,Габидов Александр Сергеевич,2,1.1,104.0,https://vk.com/topic-33327655_27333029,2012-11-04 22:31:00,NaN,1,https://vk.com/wall-33327655_725,...,2012-11-04 22:31:00,1,1,1,Младшие курсы,Фундаментальная математика,Математика,2012,0,"Я хотел бы вступить в Студенческий Совет, чтоб..."

In [17]:
ys_df.to_csv('ssmm_full_applications.csv', sep='\t', encoding='utf-8', index=False)

# 3. Management table

In [5]:
ssmm_full_management_1_11 = pd.read_csv('../library: main/ssmm_full_management_1_11.csv', sep='\t', encoding='utf-8')
ssmm_full_management_1_11.head()

,convocation_no,position,name,position_short,position_type,working_group_name,short_working_group_name,constant_flg,MSU_council_member_flg,vice_flg
0,1,Второй заместитель представителей в Студсовете...,Владыкина Вероника Евгеньевна,Заместитель представителей в Студсовете МГУ,Представительская должность,NaN,NaN,NaN,0.0,1.0
1,1,Второй представитель в Студсовете МГУ,Савушкин Никита Максимович,Представитель в Студсовете МГУ,Представительская должность,NaN,NaN,NaN,1.0,0.0
2,1,Заместитель председателя,Асташов Дмитрий Сергеевич,Заместитель председателя,Руководящая должность,NaN,NaN,NaN,0.0,1.0
3,1,Координатор РГ «Бытовые вопросы»,Котляров Никита Владимирович,Координатор,Руководящая должность,Бытовые вопросы,Бытовые вопросы,1.0,NaN,NaN
4,1,Координатор РГ «Образование»,Владыкина Вероника Евгеньевна,Координатор,Руководящая должность,Образование,Образование,1.0,NaN,NaN

In [14]:
ssmm_full_management_1_11.to_csv('ssmm_full_management.csv', sep='\t', encoding='utf-8', index=False)